## 1. Convert String Column into Date Type

In [ ]:

import pandas as pd

# Sample DataFrame
data = {
    'date': ['2023-10-01', '2023-10-02', '2023-10-03'],
    'value': [10, 20, 30]
}
df = pd.DataFrame(data)
print(type(df.date[0]))

# Convert 'date' column to datetime
df['date'] = pd.to_datetime(df['date'])
print(df)
print(type(df.date[0]))

<class 'str'>
        date  value
0 2023-10-01     10
1 2023-10-02     20
2 2023-10-03     30
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

# Practice Problem:
Set the timestamp column as the index of the DataFrame from the previous practice problem.

Hint: Use `df.set_index('Date', inplace=True)` after ensuring the column is parsed as datetime.

In [ ]:
import pandas as pd

# Self-contained example replacing external CSV read
example_dates = pd.date_range(start='2023-10-01', periods=5, freq='D')
df = pd.DataFrame({'Date': example_dates, 'value': [10, 20, None, 40, 50]})
df.set_index('Date', inplace=True)
df

            value
Date
2023-10-01   10.0
2023-10-02   20.0
2023-10-03    NaN
2023-10-04   40.0
2023-10-05   50.0

In [ ]:
# Skipping Google Colab drive mounting for local execution

# 2. Use Date as an Index of DataFrame Using set_index()
Example Problem:
Set the date column as the index of the DataFrame.

In [ ]:
# Sample DataFrame
data = {
    'date': ['2023-10-01', '2023-10-02', '2023-10-03'],
    'value': [10, 20, 30]
}
df = pd.DataFrame(data)
df['date'] = pd.to_datetime(df['date'])

# Set 'date' column as index
df.set_index('date', inplace=True)
print(df)

            value
date
2023-10-01     10
2023-10-02     20
2023-10-03     30

In [ ]:
# Already set index above; reusing the same df
print(df)

            value
date
2023-10-01     10
2023-10-02     20
2023-10-03     30

# 3. Use fillna() Method in DataFrame
Example Problem:
Replace missing values in the value column with 0.

In [ ]:
import numpy as np

# Sample DataFrame with missing values
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-03']),
    'value': [10, np.nan, 30]
}
df = pd.DataFrame(data)

# Replace NaN with 0
df['value'].fillna(0, inplace=True)
print(df)

        date  value
0 2023-10-01   10.0
1 2023-10-02    0.0
2 2023-10-03   30.0

/tmp/ipykernel_612/3457321689.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].fillna(0, inplace=True)

# Practice Problem:
Replace missing values in the value column with the mean of the column.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-03']),
    'value': [10, np.nan, 30]
}
df = pd.DataFrame(data)
df['value'].fillna(df['value'].mean(), inplace=True)
print(df)

        date  value
0 2023-10-01   10.0
1 2023-10-02   20.0
2 2023-10-03   30.0

/tmp/ipykernel_612/524048652.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].fillna(df['value'].mean(), inplace=True)

# 4. Use fillna(method="ffill") Method in DataFrame
Example Problem:
Forward fill missing values in the value column.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-03']),
    'value': [10, np.nan, 30]
}
df = pd.DataFrame(data)
df['value'].fillna(method='ffill', inplace=True)
print(df)

        date  value
0 2023-10-01   10.0
1 2023-10-02   10.0
2 2023-10-03   30.0

/tmp/ipykernel_612/3893659132.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_612/3893659132.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['value'].fillna(method='ffill', inplace=True)

# Practice Problem:
Forward fill missing values in the value column of the following DataFrame.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-03', '2023-10-04']),
    'value': [40, np.nan, 90, np.nan]
}
df = pd.DataFrame(data)
df['value'].fillna(method='ffill', inplace=True)
print(df)

        date  value
0 2023-10-01   40.0
1 2023-10-02   40.0
2 2023-10-03   90.0
3 2023-10-04   90.0

/tmp/ipykernel_612/2462491412.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_612/2462491412.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['value'].fillna(method='ffill', inplace=True)

# 5. Use fillna(method="bfill") Method in DataFrame
Example Problem:
Backward fill missing values in the value column.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-03']),
    'value': [10, np.nan, 30]
}
df = pd.DataFrame(data)
df['value'].fillna(method='bfill', inplace=True)
print(df)

        date  value
0 2023-10-01   10.0
1 2023-10-02   30.0
2 2023-10-03   30.0

/tmp/ipykernel_612/4186764907.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].fillna(method='bfill', inplace=True)
/tmp/ipykernel_612/4186764907.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['value'].fillna(method='bfill', inplace=True)

# Practice Problem:
Backward fill missing values in the value column of the following DataFrame.

In [ ]:
data = {
    'time' : pd.to_datetime(['10:00 AM', '10:15 AM', '10:30 AM', '10:45 AM'], format = '%I:%M %p'),
    'temperature' : [20, 25, np.nan, 28]
}
df = pd.DataFrame(data)
df['temperature'].fillna(method='bfill', inplace=True)
print(df)

                 time  temperature
0 1900-01-01 10:00:00         20.0
1 1900-01-01 10:15:00         25.0
2 1900-01-01 10:30:00         28.0
3 1900-01-01 10:45:00         28.0

/tmp/ipykernel_612/4269592731.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['temperature'].fillna(method='bfill', inplace=True)
/tmp/ipykernel_612/4269592731.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['temperature'].fillna(method='bfill', inplace=True)

# 6. "axis" Parameter in fillna() Method
Example Problem:
Replace missing values column-wise (axis=1)

In [ ]:
# Column-wise fillna example on a small demo DataFrame
df_axis = pd.DataFrame({'A': [1, None, 3],
                        'B': [None, 5, None]
                        })
df_axis.fillna(method = 'ffill', axis=1, inplace=True)
print(df_axis)

     A    B
0  1.0  1.0
1  NaN  5.0
2  3.0  3.0

/tmp/ipykernel_612/4285236250.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_axis.fillna(method = 'ffill', axis=1, inplace=True)

# Practice Problem:
Replace missing values row-wise (axis=0) in the following DataFrame.

In [ ]:
df_axis = pd.DataFrame({
    'A': [1, None, 3],
    'B': [None, 5, None]
    })
df_axis.fillna(method = 'ffill' , axis=0, inplace=True)
print(df_axis)

     A    B
0  1.0  NaN
1  1.0  5.0
2  3.0  5.0

/tmp/ipykernel_612/1269659422.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_axis.fillna(method = 'ffill' , axis=0, inplace=True)

# 7. "limit" Parameter in fillna() Method
Example Problem:
Replace only the first missing value in the value column.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-03']),
    'value': [10, np.nan, 30]
}
df = pd.DataFrame(data)
df['value'].fillna(15, limit=1, inplace=True)
print(df)

        date  value
0 2023-10-01   10.0
1 2023-10-02   15.0
2 2023-10-03   30.0

/tmp/ipykernel_612/3928778512.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].fillna(15, limit=1, inplace=True)

# Practice Problem:
Replace only the first two missing values in the value column of the following DataFrame.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-03', '2023-10-04', '2023-10-05']),
    'value': [10, np.nan, 30, np.nan, np.nan]
}
df = pd.DataFrame(data)
df['value'].fillna(18, limit=2, inplace=True)
print(df)

        date  value
0 2023-10-01   10.0
1 2023-10-02   18.0
2 2023-10-03   30.0
3 2023-10-04   18.0
4 2023-10-05    NaN

/tmp/ipykernel_612/3858298373.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].fillna(18, limit=2, inplace=True)

# 8. interpolate() to Do Interpolation in DataFrame
Example Problem:
Interpolate missing values in the value column.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-03', '2023-10-04', '2023-10-05']),
    'value': [10, np.nan, 30, np.nan, np.nan]
}
df = pd.DataFrame(data)
df['value'].interpolate(inplace=True)
print(df)

        date  value
0 2023-10-01   10.0
1 2023-10-02   20.0
2 2023-10-03   30.0
3 2023-10-04   30.0
4 2023-10-05   30.0

/tmp/ipykernel_612/3691691816.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].interpolate(inplace=True)

# Practice Problem:
Interpolate missing values in the value column of the following DataFrame.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-03']),
    'value': [16, np.nan, 40]
}
df = pd.DataFrame(data)
df['value'].interpolate(inplace=True)
print(df)

        date  value
0 2023-10-01   16.0
1 2023-10-02   28.0
2 2023-10-03   40.0

/tmp/ipykernel_612/99314939.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].interpolate(inplace=True)

# 9. interpolate() Method with "time"
Example Problem:
Interpolate missing values in the value column using time-based interpolation.

In [ ]:
# If index is datetime, time-based interpolation is meaningful
# Here we already have a DatetimeIndex on df
print(df)

        date  value
0 2023-10-01   16.0
1 2023-10-02   28.0
2 2023-10-03   40.0

# Practice Problem:
Interpolate missing values in the value column of the following DataFrame using time-based interpolation.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-03', '2023-10-06']),
    'value': [10, np.nan, 40]
}
df = pd.DataFrame(data)

# Set the date column as the index for time-based interpolation
df = df.set_index('date')

# Interpolate missing values using time-based interpolation
df['value'].interpolate(method='time', inplace=True)
print(df)

            value
date
2023-10-01   10.0
2023-10-03   22.0
2023-10-06   40.0

/tmp/ipykernel_612/1156010661.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['value'].interpolate(method='time', inplace=True)

# 10. dropna() Method to Drop Rows with Missing Values
Example Problem:
Drop all rows with missing values.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-03', '2023-10-06']),
    'value': [10, np.nan, 40]
}
df = pd.DataFrame(data)
df.dropna(inplace=True)
print(df)

        date  value
0 2023-10-01   10.0
2 2023-10-06   40.0

# Practice Problem:
Drop all rows with missing values in the following DataFrame.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '', '2023-10-06']),
    'value': [10, np.nan, 40],
    'temperature' : [20, np.nan, np.nan]
}
df = pd.DataFrame(data)
df.dropna(how='all', inplace=True)
df

        date  value  temperature
0 2023-10-01   10.0         20.0
2 2023-10-06   40.0          NaN

# 11. "how" Parameter in dropna() Method
Example Problem:
Drop rows where all values are missing.

In [ ]:
df.dropna(how='all', inplace=True)
print(df)

        date  value  temperature
0 2023-10-01   10.0         20.0
2 2023-10-06   40.0          NaN

# Practice Problem:
Drop rows where any value is missing in the following DataFrame.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '', '2023-10-06']),
    'value': [10, np.nan, 40],
    'temperature' : [20, np.nan, np.nan]
}
df = pd.DataFrame(data)
df.dropna(how='any', inplace=True)
df

        date  value  temperature
0 2023-10-01   10.0         20.0

# 12. "thresh" Parameter in dropna() Method
Example Problem:
Drop rows with fewer than 2 non-missing values.

In [ ]:
df.dropna(thresh=2, inplace=True)
print(df)

        date  value  temperature
0 2023-10-01   10.0         20.0

# Practice Problem:
Drop rows with fewer than 3 non-missing values in the following DataFrame.

In [ ]:
data = {
    'date': pd.to_datetime(['2023-10-01', '2023-10-02', '2023-10-06']),
    'value': [10, 20, 40],
    'temperature' : [20, 30, np.nan]
}
df = pd.DataFrame(data)
df.dropna(thresh = 3, inplace=True)
df

        date  value  temperature
0 2023-10-01     10         20.0
1 2023-10-02     20         30.0

In [ ]:
# Skipping Colab-specific file upload for local execution