## Read/Write CSV and Excel Files in Pandas</font>

### Read CSV</color>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("stocks_weather.xlsx")
df

   Unnamed: 0       day  temperature  event
0           0  1/1/2017           32   Rain
1           1  1/2/2017           35  Sunny
2           2  1/3/2017           28   Snow

In [ ]:
df1 = df.drop(columns=['Unnamed: 0'])
display(df1)

        day  temperature  event
0  1/1/2017           32   Rain
1  1/2/2017           35  Sunny
2  1/3/2017           28   Snow

In [ ]:
# This cell now uses the 'df1' DataFrame, which was created by removing the 'Unnamed: 0' column from the original 'df'
print("Continuing with the updated df1 DataFrame:")
display(df1)

Continuing with the updated df1 DataFrame:

        day  temperature  event
0  1/1/2017           32   Rain
1  1/2/2017           35  Sunny
2  1/3/2017           28   Snow

In [ ]:
# To remove the first row of df1:
df1_skipped_row = df1.iloc[1:]

print("df1 after skipping the first row:")
display(df1_skipped_row)

df1 after skipping the first row:

        day  temperature  event
1  1/2/2017           35  Sunny
2  1/3/2017           28   Snow

This creates a new DataFrame `df1_skipped_row` that contains all rows from `df1` except for the very first one.

In [ ]:
df = pd.read_csv("stock_data.csv", header=0)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv("stock_data.csv",  nrows=2)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

In [ ]:
df = pd.read_csv("stock_data.csv", na_values=["n.a.", "not available"])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [ ]:
df = pd.read_csv("stock_data.csv",  na_values={
        'eps': ['not available'],
        'revenue': [-1],
        'people': ['not available','n.a.'],
        "price" : ['n.a.']
    })
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

###Write to CSV</color>

In [ ]:
df.to_csv("new.csv", index=False)

In [ ]:
df.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [ ]:
df.to_csv("new.csv",header=False)

In [ ]:
df.to_csv("new.csv", columns=["tickers","price"], index=False)

### Read Excel</color>

In [ ]:
df = pd.read_csv("new.csv")
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

###Write to Excel</color>