## Solved Examples

### Example 1: Replace a Single Value with `NaN`

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Dave'],
    'Age': [25, -99999, 30, -99999],
    'Salary': [50000, -99999, 60000, 70000]
}
df = pd.DataFrame(data)

In [ ]:
# Replace -99999 with NaN

df_replaced = df.replace(-99999, np.nan)
print("After replacing -99999 with NaN:")
print(df_replaced)

After replacing -99999 with NaN:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN      NaN
2  Charlie  30.0  60000.0
3     Dave   NaN  70000.0

# Example 2: Replace Multiple Values Using a Dictionary
### Replace specific values in specific columns

In [ ]:
replace_dict = {
    'Age': {-99999: np.nan},
    'Salary': {-99999: np.nan, 70000: 75000}
}
df_replaced_dict = df.replace(replace_dict)
print("\nAfter replacing values using a dictionary:")
print(df_replaced_dict)

After replacing values using a dictionary:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN      NaN
2  Charlie  30.0  60000.0
3     Dave   NaN  75000.0

# Example 3: Using `regex` to Replace Values
### Create a sample DataFrame with strings

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Dave'],
    'Email': ['alice@example.com', 'bob@test.com', 'charlie@demo.com', 'dave@sample.com']
}
df_strings = pd.DataFrame(data)

In [ ]:
# Replace email domains using regex
df_regex = df_strings.replace({'Email': r'@.*\.'}, '@newdomain.', regex=True)
print("\nAfter replacing email domains using regex:")
print(df_regex)

After replacing email domains using regex:
      Name                  Email
0    Alice    alice@newdomain.com
1      Bob      bob@newdomain.com
2  Charlie  charlie@newdomain.com
3     Dave     dave@newdomain.com

# Practice Problems

### Problem 1: Replace Missing Values

* Create a DataFrame with the following data:
Name Age Salary
Alice 25 50000
Bob -1 60000
Charlie 30 -99999
Dave -99999 70000
Replace `-1` and `-99999` with `NaN` in the entire DataFrame.

In [ ]:
import numpy as np

data = {
    'Name' : ['Zainab' , 'Nida' , 'Noor' , 'minhail'],
    'Age'  : [21, -8 , 17 , 22],
    'Score' : [100, 93, 101 , -55]
}
df = pd.DataFrame(data)
df.replace(to_replace = [-8, 101, -55], value = 0 , inplace=True)
print(df)

      Name  Age  Score
0   Zainab   21    100
1     Nida    0     93
2     Noor   17      0
3  minhail   22      0

### Problem 2: Replace Values in Specific Columns
Using the same DataFrame from Problem 1, replace `-99999` with `NaN` only in the `Age` column and replace `-1` with `0` only in the `Salary` column.

In [ ]:
# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Dave'],
    'Age': [25, -99999, 30, -99999],
    'Salary': [50000, -1, 60000, 70000]
}
df = pd.DataFrame(data)
df.replace({
    'Age' : {
        -99999 : np.nan
},
    'Salary' : {
        -1 : 0
    }
}, inplace = True)
df

      Name   Age  Salary
0    Alice  25.0   50000
1      Bob   NaN       0
2  Charlie  30.0   60000
3     Dave   NaN   70000

Product Price Discount
A 100 n.a.
B 200 not available
C 300 10%
D 400 n.a.

### Problem 3: Replace Using a Dictionary
Create a DataFrame with the following data:

Replace `n.a.` and `not available` in the `Discount` column with `0%`.

In [ ]:
from decorator import DEF
data = {
    'Product': ['A', 'B', 'C', 'D'],
    'Price': [100, 200, 300, 400],
    'Discount': ['n.a.', 'not available', '10%', 'n.a.']
}
df = pd.DataFrame(data)
df['Discount'].replace(['n.a.', 'not available'], '0%', inplace=True)
df

/tmp/ipykernel_1065/981682119.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount'].replace(['n.a.', 'not available'], '0%', inplace=True)

  Product  Price Discount
0       A    100       0%
1       B    200       0%
2       C    300      10%
3       D    400       0%

### Problem 4: Replace Using `regex`
Create a DataFrame with the following data:

Replace all email domains with `@newdomain.com` using `regex`.

In [ ]:
data = {
    'Message': [
        "Contact us at info@example.com",
        "Support: support@test.com",
        "Feedback: feedback@demo.com"
    ]
}
df = pd.DataFrame(data)
df['Message'] = df['Message'].str.replace(r'@\w+\.\w+', '@newdomain.com', regex=True)
df

                            Message
0  Contact us at info@newdomain.com
1    Support: support@newdomain.com
2  Feedback: feedback@newdomain.com

### Problem 5: Replace Lists of Values
Create a DataFrame with the following data:

Category Value
A 10
B 20
C 30
D 40

Replace the values `[10, 20]` with `[100, 200]` in the `Value` column.

In [ ]:
data = {
    'Category': ['A', 'B', 'C', 'D'],
    'Value': [10, 20, 30, 40]
}

df = pd.DataFrame(data)

# Replace 10 with 100 and 20 with 200 in the 'Value' column
df.replace([10, 20], [100, 200], inplace=True)
df

  Category  Value
0        A    100
1        B    200
2        C     30
3        D     40

### Problem 6: Replace with Conditions
Create a DataFrame with the following data:

Name Score
Alice 85
Bob 45
Charlie 90
Dave 50

Replace all scores less than `50` with `Fail` and scores greater than or equal to `50` with `Pass`.

In [ ]:
df = pd.DataFrame({
    'Name' : ['Alice','Bob','Charlie', 'Dave'],
    'Score' : [85 , 45 , 90 , 50]
})

df['Score'] = df['Score'].apply(lambda x: "Pass" if x >= 50 else "Fail")

print(df)

      Name Score
0    Alice  Pass
1      Bob  Fail
2  Charlie  Pass
3     Dave  Pass

### Problem 7: Replace with Mapping
Create a DataFrame with the following data:

Grade
A
B
C
D
F

Replace the grades with their corresponding descriptions:
- `A` -> Excellent
- `B` -> Good
- `C` -> Average
- `D` -> Poor
- `F` -> Fail

In [ ]:
df = pd.DataFrame({
    'Grade' : ['A', 'B', 'C', 'D', 'F']
})

# Replace letter grades with descriptions
df['Grade'].replace(['A', 'B', 'C', 'D', 'F'],
                    ['Excellent', 'Good', 'Average', 'Poor', 'Fail'],
                    inplace=True)

print(df)

       Grade
0  Excellent
1       Good
2    Average
3       Poor
4       Fail

/tmp/ipykernel_1065/867262543.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Grade'].replace(['A', 'B', 'C', 'D', 'F'],